### ISSUE TITLE
Channel Alignment 0.85 check in feedback

### ISSUE THREAD

**Issue by xinyang2k** [chipsalliance/aib-protocols#25] opened 2021-09-21 05:19 UTC
![image](https://user-images.githubusercontent.com/47224718/134114888-5de12f5c-9596-4402-ba55-3fce5308386d.png)

The above is the state machine from ca_rx_align.sv. There are three questions:
1.  The previous condition is | fifo_full. Now changed to |wr_overflow_pulse. I don't know the reason for this change. But if any of the fifo is full, it is good enough reason to go to error state. It does not  need to wait until overflow. Also, whence it go to full, I assume the FIFO should stay full till softreset.
2.  RX_MON state here is an orphan state. No path to go to this state. Can you double check for this error?
3.  There should be way to get out of this state once some error happens. At least if align_fly is enabled.

**Comment by nij-intel** [comment] 2021-09-22 21:05
Julie to analyze the expected behavior of align_fly after align_done is asserted

**Comment by dkehlet** [comment] 2021-09-23 19:30
Hello all, since the HAS, FS and PDR are mute on the subject, I suggest we add this to the FS description of align_fly:

If align_fly changes from 1’b0 to 1’b1, the module starts dynamically aligning the channels. Any earlier align_err as 1’b1 or align_done as 1’b1 is cleared. If align_fly changes from 1’b1 to 1’b0, the module stops dynamic alignment.

**Comment by johna-eximiusdesign** [comment] 2021-09-23 19:46
Dave, I agree the HAS was very unclear on the feature requirements. This is why an extensive conversation was had with Julie on GiHub issue #7 teasing out the details. This is also why GitHub issue #25 (and #21) is marked as a duplicate since this issue was discussed in detail GiHub issue #7.

In GiHub issue #7, there was a clear definition of the feature, explicitly signed off by Julie, which is what we have implemented. Specifically that align_fly only allows us to exit from an align_err state. Once we are in align_done state, we stay in that state forever.

The new feature being requested here will result in corruption of receive data, loss of valid receive data, and persistent loss of flow control.

**Comment by dkehlet** [comment] 2021-09-23 20:01
Duplicate of 7.

**Closed by dkehlet** 2021-09-23 20:01 UTC
Labels: duplicate
